### ISSUE TITLE
Does not compile with rustc beta

### ISSUE THREAD

**Issue by vasily-kirichenko** [mitsuhiko/rust-sha1#11]
Today Rust 1.0.0 beta has been released and it turns out this crate does not compile with it:

```
C:\Users\kot\.cargo\registry\src\github.com-1ecc6299db9ec823\sha1-0.0.8\src\lib.rs:16:1: 16:25 error: unstable feature
C:\Users\kot\.cargo\registry\src\github.com-1ecc6299db9ec823\sha1-0.0.8\src\lib.rs:16 #![feature(collections)]
                                                                                      ^~~~~~~~~~~~~~
```

note: this feature may not be used in the beta release channel
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
Could not compile `sha1`.

Caused by:
  Process didn't exit successfully: `rustc C:\Users\kot\.cargo\registry\src\github.com-1ecc6299db9ec823\sha1-0.0.8\src\lib.rs --crate-name sha1 --crate-type lib -g -C metadata=2e80406a5f497696 -C extra-filename=-2e80406a5f497696 --out-dir D:\git\rust\rust_test1\target\debug\deps --emit=dep-info,link -L dependency=D:\git\rust\rust_test1\target\debug\deps -L dependency=D:\git\rust\rust_test1\target\debug\deps --extern byteorder=D:\git\rust\rust_test1\target\debug\deps\libbyteorder-919e9a7c69df6496.rlib -Awarnings` (exit code: 101)
d:\git\rust\rust_test1>cargo build --verbose > l.log
C:\Users\kot.cargo\registry\src\github.com-1ecc6299db9ec823\sha1-0.0.8\src\lib.rs:16:1: 16:25 error: unstable feature
C:\Users\kot.cargo\registry\src\github.com-1ecc6299db9ec823\sha1-0.0.8\src\lib.rs:16 #![feature(collections)]
                                                                                      ^~~~~~~~~~~~~~

```
note: this feature may not be used in the beta release channel
error: aborting due to previous error
Could not compile `sha1`.

Caused by:
  Process didn't exit successfully: `rustc C:\Users\kot\.cargo\registry\src\github.com-1ecc6299db9ec823\sha1-0.0.8\src\lib.rs --crate-name sha1 --crate-type lib -g -C metadata=2e80406a5f497696 -C extra-filename=-2e80406a5f497696 --out-dir D:\git\rust\rust_test1\target\debug\deps --emit=dep-info,link -L dependency=D:\git\rust\rust_test1\target\debug\deps -L dependency=D:\git\rust\rust_test1\target\debug\deps --extern byteorder=D:\git\rust\rust_test1\target\debug\deps\libbyteorder-919e9a7c69df6496.rlib -Awarnings` (exit code: 101)
```

**Comment by mitsuhiko** [comment]
I have no plans on supporting the beta channel.  I depend on unstable functionality.

**Comment by mitsuhiko** [comment]
I actually managed to make that crate work with beta now.  So that should be fine now.

**Comment by vasily-kirichenko** [comment]
Great, it actually compiles now. Thanks.
