### ISSUE TITLE
Why are PartialOrd, PartialEq, Ord, Eq not implemented?

### ISSUE THREAD

**Issue by matthiasbeyer** [mitsuhiko/rust-sha1#23]
Hi,

why are these traits are not implemented for the `Sha1` or `Digest` types?

**Comment by mitsuhiko** [comment]
I don't think there is a good reason. Could be added.

**Comment by matthiasbeyer** [comment]
I'd love to submit a PR, maybe today evening!

**Comment by mitsuhiko** [comment]
Would be cool!

**Comment by matthiasbeyer** [comment]
Well... now I know! We cannot derive them because `[u8; 64]` does not allow deriving them.

I could implement this, although I'm not sure I'd be able to implement a fast algorithm here.
