### ISSUE TITLE
Enabling std feature doesnt seem to actually use std features

### ISSUE THREAD

**Issue by kinggoesgaming** [mitsuhiko/rust-sha1#30]
Testing around I didn't find anything in particular that would be causing this.

Particular issue that made me aware of the issue: `DigestParseError` doesnt implement `std::error::Error`:

https://i.imgur.com/v2RND5Z.png https://i.imgur.com/POSG6j3.png

Ref: uuid-rs/uuid#144

**Comment by mitsuhiko** [comment]
I'm not entirely understanding what's happening here. The digest parse error is defined like this:

```rust
#[cfg(feature="std")]
impl std::error::Error for DigestParseError {
    fn description(&self) -> &str {
        "not a valid sha1 hash"
    }
}
```

**Comment by kinggoesgaming** [comment]
Thats what really confused me, since that should ideally work. I have been messing around with a local clone of the project trying this to work. building the `sha1` crate itself this seems to work but when using it from another crate error seems to not exist

**Comment by badboy** [comment]
That looks more like the additional feature is not set at all, also indicated by the warnings.

**Comment by mitsuhiko** [comment]
Going to close this here. This seems unrelated to this crate.

**Comment by kinggoesgaming** [comment]
Right, this definitely sha1 -> uuid interaction going wrong.

I asked for help on the users forum, although no one came forward https://users.rust-lang.org/t/need-help-with-feature-gates-because-cargo-and-feature-gates-are-fun-ie-not/15602

I have more details there that you can look at.

**edit**: woops ate words... fixed
