### ISSUE TITLE
Would You Like If I Implemented the `digest` Traits?

### ISSUE THREAD

**Issue by zicklag** [mitsuhiko/rust-sha1#37]
Hey there, I needed to generate an HMAC-SHA1 hash in an application of mine and to do so I needed to implement the traits from the [`digest`](https://docs.rs/digest) crate in order to make it compatible with the [`hmac`](https://docs.rs/hmac) crate. Would you be interested in a PR to implement the digest traits so that users don't have to do this themselves?

It could be behind a feature gate to prevent pulling in an unneeded dependency if such support is not required.

**Comment by danieldulaney** [comment]
My understanding is that the digest crate is part of the RustCrypto ecosystem. You might be interested in the [sha-1](https://crates.io/crates/sha-1) crate (note the hyphen!), which is by the RustCrypto developers.

This crate is meant to be as minimal as possible and has zero dependencies, which helps reduce code size and complexity at the cost of reduced compatibility with other crates. It's not the only design approach possible, but it can be useful in some circumstances.
