### ISSUE TITLE
[Q&A] Does this crate implement 'hardened' SHA1?

### ISSUE THREAD

**Issue by Byron** [mitsuhiko/rust-sha1#43]
I am using this crate over at `gitoxide` for pure Rust builds and this question was ask on [reddit](https://www.reddit.com/r/rust/comments/yo1hb1/comment/ivcmy8b/?utm_source=share&utm_medium=web2x&context=3) recently.

Also I am putting 'hardened' in quotes as I don't know if it's the correct term, but it's used in [the `git` documentation](https://github.com/git/git/blob/master/Documentation/technical/hash-function-transition.txt#L34:L36) accordingly.

Thank you

**Comment by mitsuhiko** [comment]
It does not. Hardened SHA1 in a sense is a collision detection in the hash generation. It's unclear to me if that is something that should be added to this crate. I think most users of this crate "just" need a SHA1 for basic cases such as checksum or uuid generation. For more secure uses a different hash function should be used to begin with.

If SHA1 is needed, and hardening is needed I would propose to upstream this into the rust crypto SHA1 crate.
