### ISSUE TITLE
Not that secure - might consider redirecting for safer alternative

### ISSUE THREAD

**Issue by techtonik** [mitsuhiko/rust-sha1#9]
http://googleonlinesecurity.blogspot.co.uk/2014/09/gradually-sunsetting-sha-1.html

**Comment by badboy** [comment]
That doesn't make this crate useless. There are valid use cases for it. In fact there are many many programs out there still relying on sha1, git being among them.
Redirecting if sha1 is exactly what is needed makes no sense

**Comment by techtonik** [comment]
Providing info when sha1 is exactly what is needed is a must IMHO.

**Comment by mitsuhiko** [comment]
Irrelevant for this crate.
